### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by akx** [alxlu/suppress-chunks-webpack-plugin#15]
Any chance for a `suppress-chunks-webpack-plugin` 2.0.0 release with #11 to get rid of this core-js@2 warning? :)

> **warning** suppress-chunks-webpack-plugin > core-js@2.6.11:
>   core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**Comment by akx** [comment]
@alxlu Ping (and sorry :) )

**Comment by alxlu** [comment]
@akx hi sorry! It should now be published as `1.0.6`!
![image](https://user-images.githubusercontent.com/3271834/74421461-ead54280-4e01-11ea-8349-9808b437b2b0.png)

**Comment by alxlu** [comment]
let me know if it works for you

**Comment by akx** [comment]
Works fine, thanks! 👍
